spring:
  application:
    name: proxy_node
  mail:
    # 指定邮件服务器地址
    host: smtp.qiye.aliyun.com
    # 登录账户
    username: linux@xlike.email
    # 登录密码
    password: "123456"
    # 端口
    port: 25
    # 默认编码
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtp
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          host: smtp.qiye.aliyun.com   #阿里云
          port: 465
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
        debug: true
server:
  port: 9988